# Generated by Django 2.1.5 on 2019-04-16 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('ssrid', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=75)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
