# Generated by Django 2.1.5 on 2019-04-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_posts_mainimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='mainimg',
            field=models.ImageField(default='static/projects/1.jpg', upload_to='static/projects/'),
        ),
    ]
