# Generated by Django 2.1.5 on 2019-04-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190418_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='mainimg',
            field=models.ImageField(default='static/project/1.jpg', upload_to='static/project/'),
        ),
    ]
