# Generated by Django 2.1.5 on 2019-04-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='mainimg',
        ),
    ]
