# Generated by Django 2.1.5 on 2019-04-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_posts_mainimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='mission',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
