# Generated by Django 2.1.5 on 2019-04-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190418_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='mission',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
