# Generated by Django 2.1.5 on 2019-04-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190418_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='mission',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
