# Generated by Django 2.1.5 on 2019-04-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190418_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='mission',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
