# Generated by Django 2.1.5 on 2019-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('1', 'Awareness'), ('2', 'Flood Relief')], max_length=50),
        ),
    ]
