# Generated by Django 2.1.5 on 2019-04-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190418_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('1', 'Awareness'), ('2', 'Self Defence'), ('3', 'Medical Camp'), ('4', 'Skill Building'), ('5', 'Yoga'), ('6', 'Career Guidance'), ('7', 'Cleanup Drive'), ('8', 'Organic Farming'), ('9', 'Waste Management & Composting'), ('10', 'Go Green'), ('11', 'Safety & Security'), ('12', 'Health & Hygiene'), ('13', 'Flood Relief'), ('14', 'Orphanage'), ('15', 'Social awareness'), ('16', 'Rennovation'), ('17', 'Construction')], max_length=50),
        ),
    ]
