# Generated by Django 2.1.5 on 2019-04-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190420_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='mission',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
