# Generated by Django 2.1.5 on 2019-04-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190420_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='video',
            field=models.URLField(default='https://www.youtube.com/embed/8O3df8lXOME'),
        ),
    ]
