# Generated by Django 2.1.5 on 2019-04-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default=' ', max_length=75),
        ),
    ]
