# Generated by Django 2.1.5 on 2019-04-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20190421_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.AddField(
            model_name='comments',
            name='ssrid',
            field=models.CharField(default='', max_length=9),
        ),
    ]
