# Generated by Django 2.1.5 on 2019-04-22 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190421_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
