# Generated by Django 2.1.5 on 2019-04-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20190422_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
