# Generated by Django 2.1.5 on 2019-04-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20190422_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.CharField(default='awareness, self defence, medical camp, skill building, yoga, career guidance, cleanup drive, organic farming, waste management and composting, go green, safety and security, health and hygiene, flood relief, orphanage, social awareness, rennovation, construction', max_length=200),
        ),
    ]
