# Generated by Django 2.1.5 on 2019-04-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20190422_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='ssrid',
        ),
        migrations.AddField(
            model_name='comments',
            name='ssrid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Posts'),
        ),
    ]
