# Generated by Django 2.1.5 on 2019-04-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20190422_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='ssrid',
            field=models.CharField(max_length=9),
        ),
    ]
