# Generated by Django 2.1.5 on 2019-04-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20190422_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='static/project/main.jpg', upload_to='static/main/'),
        ),
    ]
